n1 = input("Digite algo?")
print ("qual o tipo? ", type(n1))
print ("Tem Espaço? ", n1.isspace())
print ("é um número? ", n1.isnumeric())
print ("é alfabético? ", n1.isalpha())
print ("é alfanúmerico? ", n1.isalnum())
print ("Esta em maiúsculo? ", n1.isupper())
print ("Está em minúsculo? ", n1.islower())
print ("Está capitalizada? ", n1.istitle())